; Wifiduino32S3 —— WiFi 网页控制 LED 闪烁频率
[env:wifiduino32s3]
platform = espressif32@6.9.0   ; 固定版本，对应 arduino-esp32 2.0.17（ledcSetup API）
board = wifiduino32s3
framework = arduino
monitor_speed = 115200
